import './globals.css';
import './preflight.css';

import type React from 'react';

import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';

import Providers from './providers';

const inter = Public_Sans({ subsets: ['latin'], variable: '--primary-font' });

export const metadata: Metadata = {
  title: {
    template: '%s | Pos Semesta',
    default: '',
    absolute: 'Pos Semesta',
  },
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => (
  <html lang="en">
    <body
      className={`relative flex min-h-screen text-slate-900 selection:bg-primary-100 ${inter.className} ${inter.variable}`}
    >
      <Providers>{children}</Providers>
    </body>
  </html>
);

export default RootLayout;
